issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl

linters:
  enable:
    - asciicheck
    - bodyclose
    - dupl
    - errorlint
    - forbidigo
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - ifshort
    - makezero
    - misspell
    - nakedret
    - revive
    - whitespace

linters-settings:
    godot:
      exclude:
        - '@.+'

    govet:
      check-shadowing: true
      enable-all: true
