version: "2"
services:
  redis_db:
    image: redis:3.0
    expose:
      - 6379
    command: >
     --appendonly yes
    volumes:
      - ./redis:/data

  redmine-bot:
    build: .
    command: /app/main
    volumes:
      - $GOPATH/pkg/mod:/go/pkg/mod
    links:
      - redis_db
    depends_on:
      - redis_db
    environment:
      - TELEGRAM_BOT_KEY=$TELEGRAM_BOT_KEY
      - DEBUG=true
      - REDIS_URL=redis://redis_db:6379

